# Generated by Django 5.1.7 on 2025-03-14 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.passportregistration'),
        ),
    ]
