# Generated by Django 5.1.2 on 2025-03-25 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_passportapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportapplication',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhar Number must be exactly 12 digits.')]),
        ),
        migrations.AddField(
            model_name='passportapplication',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{10}$', 'PAN Number must be exactly 10 alphanumeric characters.')]),
        ),
        migrations.AlterField(
            model_name='passportapplication',
            name='signature_file',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
