# Generated by Django 5.1.7 on 2025-03-16 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_passportapplication_user'),
        ('verification_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=20, unique=True)),
                ('verification_date_time', models.DateTimeField(auto_now=True)),
                ('verification_status', models.CharField(choices=[('Verified', 'Verified'), ('Rejected', 'Rejected')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('admin_verification', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('passport_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.passportapplication')),
                ('verification_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification_app.employee')),
            ],
        ),
    ]
