# Generated by Django 5.1.7 on 2025-03-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification_app', '0002_passportverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passportverification',
            name='admin_verification',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passportverification',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('Verified', 'Verified'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
